
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int PLUSPLUS = 15;
  public static final int DIVIDE = 20;
  public static final int CHAR = 46;
  public static final int STRINGLIT = 51;
  public static final int RT_BRACE = 25;
  public static final int PREFIXPLUS = 18;
  public static final int SEMI = 21;
  public static final int INT = 43;
  public static final int PRINTLN = 10;
  public static final int LESS = 30;
  public static final int MINUS = 16;
  public static final int NOT = 34;
  public static final int AND = 3;
  public static final int INTLIT = 48;
  public static final int OR = 12;
  public static final int BOOL = 45;
  public static final int COMMA = 38;
  public static final int LEFT_BRACE = 24;
  public static final int CLASS = 2;
  public static final int FI = 6;
  public static final int PLUS = 14;
  public static final int IF = 5;
  public static final int CONDITION = 35;
  public static final int ID = 47;
  public static final int EOF = 0;
  public static final int MINUSMINUS = 17;
  public static final int RETURN = 11;
  public static final int GTR = 29;
  public static final int TRUE = 41;
  public static final int error = 1;
  public static final int LEFT_BRKT = 26;
  public static final int RT_PAREN = 23;
  public static final int VOID = 40;
  public static final int FLOATLIT = 49;
  public static final int ASSMNT = 37;
  public static final int EQ = 28;
  public static final int TIMES = 13;
  public static final int CHARLIT = 50;
  public static final int PREFIXMINUS = 19;
  public static final int COLON = 36;
  public static final int ELSE = 4;
  public static final int READ = 8;
  public static final int NOT_EQ = 33;
  public static final int FINAL = 39;
  public static final int WHILE = 7;
  public static final int LESS_EQ = 31;
  public static final int FLOAT = 44;
  public static final int RT_BRKT = 27;
  public static final int LEFT_PAREN = 22;
  public static final int FALSE = 42;
  public static final int GTR_EQ = 32;
  public static final int PRINT = 9;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CLASS",
  "AND",
  "ELSE",
  "IF",
  "FI",
  "WHILE",
  "READ",
  "PRINT",
  "PRINTLN",
  "RETURN",
  "OR",
  "TIMES",
  "PLUS",
  "PLUSPLUS",
  "MINUS",
  "MINUSMINUS",
  "PREFIXPLUS",
  "PREFIXMINUS",
  "DIVIDE",
  "SEMI",
  "LEFT_PAREN",
  "RT_PAREN",
  "LEFT_BRACE",
  "RT_BRACE",
  "LEFT_BRKT",
  "RT_BRKT",
  "EQ",
  "GTR",
  "LESS",
  "LESS_EQ",
  "GTR_EQ",
  "NOT_EQ",
  "NOT",
  "CONDITION",
  "COLON",
  "ASSMNT",
  "COMMA",
  "FINAL",
  "VOID",
  "TRUE",
  "FALSE",
  "INT",
  "FLOAT",
  "BOOL",
  "CHAR",
  "ID",
  "INTLIT",
  "FLOATLIT",
  "CHARLIT",
  "STRINGLIT"
  };
}

